name: Build Plugins

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build plugins
        run: npm run build:plugins

      - name: Commit dist + manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add dist manifest.json
          git commit -m "Build plugins [skip ci]" || echo "No changes"
          git push
